### ISSUE TITLE
Outdated action-install-gh-release

### ISSUE THREAD

**Issue by EnergoStalin** [pulumi/pulumi-upgrade-provider-action#7]
### What happened?

`jaxxstorm/action-install-gh-release@v1.5.0` Fails with no github token.

### Expected Behavior

Install pulumictl

### Steps to reproduce

Use action in workflow

### Output of `pulumi about`

CLI          
Version      3.75.0
Go Version   go1.20.5
Go Compiler  gc

Host     
OS       ubuntu
Version  22.04
Arch     x86_64

### Additional context

I have fix it updating action to [latest 1.10](https://github.com/jaxxstorm/action-install-gh-release/releases/tag/v1.10.0) version. but too lazy for pr.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Thanks for reporting this and providing the solution. Yes, we'll need to update the upstream dependency to [at least v1.8.0](https://github.com/jaxxstorm/action-install-gh-release/releases/tag/v1.8.0) to support this.
